# Generated by Django 2.2.3 on 2019-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_buddies', '0002_auto_20190715_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
